image: ruby:2.7

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

cache:
  paths:
    - vendor/

before_script:
  - gem install bundler
  - bundle install --path vendor

pages:
  stage: deploy
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  environment: production

test:
  stage: test
  script:
    - bundle exec jekyll build -d test
  artifacts:
    paths:
      - test
  rules:
    - if: $CI_COMMIT_BRANCH != "main"


#before_script:
#    - "apt-get update -qq"
#    - "apt-get install -qq openssh-client"
#    - mkdir -p ~/.ssh
#    - chmod 700 ~/.ssh
#    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
#    - chmod 644 ~/.ssh/known_hosts
#    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/gitlab_rsa
#    - chmod 700 ~/.ssh/gitlab_rsa
    
#deploy_staging:
#    stage: deploy
#    tags: 
#        - docker
#    environment:
#        name: staging
#        url: mig.dcs.gla.ac.uk
#    script:
#        - ssh -i ~/.ssh/gitlab_rsa euan@mig.dcs.gla.ac.uk "cd /var/www/ && git checkout master && git pull origin master && exit"
#    only:
#        - master
