image: debian

before_script:
    - "apt-get update -qq"
    - "apt-get install -qq openssh-client"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 700 $SSH_PRIVATE_KEY
    
deploy_staging:
    type: deploy
    tags: 
        - docker
    environment:
        name: staging
        url: mig.dcs.gla.ac.uk
    script:
        - ssh -i $SSH_PRIVATE_KEY euan@mig.dcs.gla.ac.uk "cd /var/www/ && git checkout master && git pull origin master && exit"
    only:
        - master
