name: Update Publications

on:
  push:
    branches:
      - IainCE-2025-auto-papers  # Change to the branch you're testing on
  workflow_dispatch:  # Allow manual triggers
  schedule:
    - cron: '0 0 * * 0'  # Runs at midnight (00:00) every Sunday (day 0)

jobs:
  update-publications:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests jinja2

      - name: Run publication update script
        run: python update_publications.py

      - name: Debug Git Status
        run: |
          git status 
          ls -R publications
      
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add --all
          git commit -m "Update publications page" || echo "No changes to commit"
          git push origin IainCE-2025-auto-papers

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publications
